// Unit tests for web/yaml-export.js. The authoritative validation is
// the Python round-trip parity test (tests/test_parity.py); this file
// guards the JS-side invariants we rely on (string quoting, flow map
// emission, schema-shape coverage).

import { test } from 'node:test';
import assert from 'node:assert/strict';

import { archToYaml } from '../../web/yaml-export.js';

function sample() {
  return {
    meta: { schema_version: '1', domain: 'airport' },
    asset_owners: [
      { id: 'APT', role: 'AO' },
      { id: 'VND', role: 'AO' },
    ],
    sp_relations: [
      { sp: 'VND', ao: 'APT', scope: ['CD-01'] },
    ],
    zone_authorities: [
      { zone: 'VLAN-IDF', org: 'APT' },
    ],
    conduits: [
      {
        id: 'CD-01',
        from: { owner: 'VND', zone: 'VLAN-IDF' },
        to:   { owner: 'APT', zone: 'VLAN-IDF' },
      },
    ],
  };
}

test('emits the required top-level sections', () => {
  const yaml = archToYaml(sample());
  assert.match(yaml, /^meta:\n/m);
  assert.match(yaml, /^asset_owners:\n/m);
  assert.match(yaml, /^sp_relations:\n/m);
  assert.match(yaml, /^zone_authorities:\n/m);
  assert.match(yaml, /^conduits:\n/m);
});

test('every string scalar is double-quoted', () => {
  const yaml = archToYaml(sample());
  // id, role, domain, zone, org etc. All quoted.
  assert.match(yaml, /id: "CD-01"/);
  assert.match(yaml, /role: "AO"/);
  assert.match(yaml, /domain: "airport"/);
  assert.match(yaml, /zone: "VLAN-IDF"/);
  assert.match(yaml, /org: "APT"/);
  // Unquoted bare tokens that could trip yaml.safe_load type coercion
  // should NOT appear where a string is expected.
  assert.doesNotMatch(yaml, /role: AO\n/);
  assert.doesNotMatch(yaml, /domain: airport\n/);
});

test('omits empty optional collections', () => {
  const arch = sample();
  delete arch.sp_relations;
  delete arch.zone_authorities;
  const yaml = archToYaml(arch);
  assert.doesNotMatch(yaml, /^sp_relations:/m);
  assert.doesNotMatch(yaml, /^zone_authorities:/m);
  assert.match(yaml, /^conduits:\n/m);
});

test('conduit description and notes are escaped to a single quoted string', () => {
  const arch = sample();
  arch.conduits[0].description = 'A rationale with "quotes" and a newline\nin it';
  arch.conduits[0].notes = 'Tab\there.';
  const yaml = archToYaml(arch);
  // Newlines and quotes in scalars become \n and \"
  assert.match(yaml, /description: "A rationale with \\"quotes\\" and a newline\\nin it"/);
  assert.match(yaml, /notes: "Tab\\there\."/);
});

test('strings that look like YAML booleans stay strings (double-quoted)', () => {
  const arch = {
    meta: { schema_version: '1', domain: 'no' }, // 'no' is a YAML boolean in YAML 1.1
    asset_owners: [
      { id: 'yes', role: 'AO' },
      { id: 'off', role: 'AO' },
    ],
    conduits: [
      {
        id: 'null',  // reserved word if unquoted
        from: { owner: 'yes' },
        to:   { owner: 'off' },
      },
    ],
  };
  const yaml = archToYaml(arch);
  assert.match(yaml, /domain: "no"/);
  assert.match(yaml, /id: "yes"/);
  assert.match(yaml, /id: "off"/);
  assert.match(yaml, /id: "null"/);
});

test('control characters in strings are escaped to \\xNN', () => {
  const arch = sample();
  arch.conduits[0].notes = 'bell\u0007here';
  const yaml = archToYaml(arch);
  assert.match(yaml, /notes: "bell\\x07here"/);
});

test('C1 controls (U+0080-U+009F) including NEL are escaped, not passed through', () => {
  // PyYAML 1.1 safe_load silently normalises raw NEL (U+0085) to ASCII space.
  // Escaping in qstr is what preserves byte-faithful round trip; this test
  // pins the escape format so a future "simplification" of qstr can't
  // regress the U+0085 case silently.
  const arch = sample();
  arch.conduits[0].notes = '\u0080\u0085\u009F';
  const yaml = archToYaml(arch);
  assert.ok(!yaml.includes('\u0085'), 'raw U+0085 must not appear in output');
  assert.ok(!yaml.includes('\u0080'), 'raw U+0080 must not appear in output');
  assert.ok(!yaml.includes('\u009F'), 'raw U+009F must not appear in output');
  assert.match(yaml, /notes: "\\x80\\x85\\x9f"/);
});

test('line/paragraph separators (U+2028, U+2029) are stripped', () => {
  const arch = sample();
  arch.conduits[0].notes = 'a\u2028b\u2029c';
  const yaml = archToYaml(arch);
  assert.ok(!yaml.includes('\u2028'), 'U+2028 leaked');
  assert.ok(!yaml.includes('\u2029'), 'U+2029 leaked');
  assert.match(yaml, /notes: "abc"/);
});

test('header comment lines prefix the document when requested', () => {
  const yaml = archToYaml(sample(), { header: 'Generated by BlindSpotCheck\nLine two' });
  assert.match(yaml, /^# Generated by BlindSpotCheck\n# Line two\n\nmeta:/);
});

test('output always ends with a single trailing newline', () => {
  const yaml = archToYaml(sample());
  assert.equal(yaml.endsWith('\n'), true);
  assert.equal(yaml.endsWith('\n\n\n'), false);
});
